sudo: true
language: c
dist: xenial
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq -y equivs devscripts valgrind colorgcc lcov
  - sudo ./prerequisites.sh
script:
  - ./autogen.sh
  - ./configure CC=$TRAVIS_CC --prefix=/usr --enable-valgrind --enable-gcov
  - make check
  - make check-valgrind
  - sudo make install
  - make distcheck
  - make distclean
  - sudo ./debian/libnss-juju.postinst configure
  - getent hosts juju-ip-1-2-3-4 > /tmp/x
  - cat /tmp/x
  - grep 1.2.3.4 /tmp/x
env:
  matrix:
    - TRAVIS_CC=colorgcc EXTRA_CFLAGS='-Wall -Werror'
after_success:
  - bash <(curl -s https://codecov.io/bash)
